### ISSUE TITLE
CONTRIBUTING.md do not exists, but referenced in README.md

### ISSUE THREAD

**Issue by rodrigomelo9** [hdl/awesome#6]
Self-explanatory :p

**Comment by eine** [comment]
Ups, I actually forgot that it existed and the "template" was defined there: https://github.com/hdl/awesome/blob/develop/.github/CONTRIBUTING.md. It's accesible from https://github.com/hdl/awesome/community. I see the issue in the README is a missing dot. I'll fix it.

Anyway, I think the template is better as a separate file.
