### ISSUE TITLE
Add 'About' and 'Contributing' sections to the site

### ISSUE THREAD

**Issue by eine** [hdl/awesome#70]
Currently, there is no page in the site for providing information which is not specific to some tool/project. We should have one or two pages, for people to know what's the purpose and how to contribute. Currently, visitors of single pages might overlook that the main motivation of this repository is for the community to participate.

**Comment by rodrigomelo9** [comment]
I can prepare both of the with a basic content, which can be improved later.

**Comment by umarcor** [comment]
This was done in #79.
