### ISSUE TITLE
What about to add logos?

### ISSUE THREAD

**Issue by rodrigomelo9** [hdl/awesome#73]
Can be stored at `static/logos` using the same base filename of the related item, and be used only if available. Is what I did at [FPGApedia](https://rodrigomelo9.gitlab.io/fpgapedia/vendors).

**Comment by umarcor** [comment]
I think that's a nice idea! Yet, unlike most companies, a lot of open source projects/tools don't have a logo. Hence, I think that displaying it on the left might not be a good idea in this theme. I suggest having it on the right (in both layouts, the list and the single page). The theme in this repository is a submodule, which points to branch `theme`. Therefore, that's the branch that needs to be modified for adding this feature.

From a licensing point of view, I'm not sure we are allowed to store the logos here, or to display them on the site! I guess that would be considered fair use, but we should add some note about it somewhere.

**Comment by rodrigomelo9** [comment]
Ok, the logo can be at the right. Yes, I know how to deal with the theme in this repo ;-)

I guess that is not a problem with a FOSS project to store an unmodified version of the logo (could be a problem with modified versions). Anyway, we can put a disclaimer (a notice) about to ask to remove them.

**Comment by umarcor** [comment]
> Anyway, we can put a disclaimer (a notice) about to ask to remove them.

Where should we put it? I'm afraid that adding it to `LICENSE.md` will break GitHub's license detection algorithm. Should it be in the README or in an About page (#70)?

**Comment by rodrigomelo9** [comment]
I like the idea of both of them (README and about), maybe with slightly different messages ( the logos stored at this repo... the logos used in this site...).
